name: Daily Bonus

on:
  push:
    branches:
      - master
  schedule:
    - cron: '07 11 * * *'

jobs:
  checkin:
    strategy:
      matrix:
        os: [self-hosted]
        # os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    env:
      V2EX_COOKIES: ${{ secrets.V2EX_COOKIES }}
      BILIBILI_COOKIES: ${{ secrets.BILIBILI_COOKIES }}
      YAMIBO_COOKIES: ${{ secrets.YAMIBO_COOKIES }}
      YURIFANS_EMAIL: ${{ secrets.YURIFANS_EMAIL }}
      YURIFANS_PASSWORD: ${{ secrets.YURIFANS_PASSWORD }}
      PICA_EMAIL: ${{ secrets.PICA_EMAIL }}
      PICA_PASSWORD: ${{ secrets.PICA_PASSWORD }}
      TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      TG_USER_ID: ${{ secrets.TG_USER_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

#      - name: Set timezone
#        run: Set-TimeZone -Id "China Standard Time"  #sudo timedatectl set-timezone 'Asia/Shanghai'  #

#      - name: Echo current time
#        run: timedatectl
        
      - name: Set timezone (Windows)
        if: matrix.os == 'self-hosted-windows'  # 仅 Windows 运行器执行
        shell: powershell
        run: |
          Set-TimeZone -Id "China Standard Time"  # Windows 专用命令
          Write-Output "时区已设置为中国标准时间"

      - name: Echo current time
        shell: powershell
        run: |
          Get-Date -Format "yyyy-MM-dd HH:mm:ss"  # 输出当前时间
          Get-TimeZone | Select-Object Id, StandardName  # 输出时区信息

      - name: Set up Python 3.8
        uses: actions/setup-python@v5
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Check-in
        run: python ./message.py
